# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Anton Averin Development Blog
tagline:             Android blog
url:                 http://aaverin.github.io
baseurl:             ""
markdown:			 redcarpet


paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Anton Averin Dev Blog

# About/contact
author:
  name:              Anton Averin
  url:               http://anton.averin.pro
  twitter:           a_a_averin
  github:            aaverin
  linkedin:          anton.averin
  email:             a.a.averin@gmail.com

rss_path: feed.xml
categories_path: categories/index.html
tags_path: tags/index.html

BASE_PATH:
