# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Anton Averin Development Blog
tagline:             Android blog
url:                 http://aaverin.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Anton Averin
  url:               http://anton.averin.pro
  email:             a.a.averin@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole

kramdown:
  input: GFM